import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Iphon 9',
      slug: 'iphon-9',
      category: 'Phones',
      image: '/images/iphon9.jpg',
      price: 70,
      brand: 'Iphon',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'The iPhone 13 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).',
      isFeatured: true,
      banner: '/images/iphon9banner.jpg',
    },
    {
      name: 'Iphon 13',
      slug: 'iphon-13',
      category: 'Phones',
      image: '/images/iphon13.jpg',
      price: 70,
      brand: 'Iphon',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'The iPhone 13 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).',
      isFeatured: true,
      banner: '/images/iphon13banner.jpg',
    },
    {
      name: 'Iphon 14',
      slug: 'iphon-14',
      category: 'Phones',
      image: '/images/iphon14.jpg',
      price: 80,
      brand: 'Iphon',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'The iPhone 14 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).',
      isFeatured: true,
      banner: '/images/iphon14banner.jpg',
    },
    {
      name: 'Iphon 15',
      slug: 'slim-shirt',
      category: 'Phones',
      image: '/images/iphon15.jpg',
      price: 90,
      brand: 'Iphon',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'The iPhone 15 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).',
      isFeatured: true,
      banner: '/images/iphon15banner.jpg',
    },
    {
      name: 'Iphon X',
      slug: 'iphon-x',
      category: 'Phones',
      image: '/images/iphonx.jpg',
      price: 90,
      brand: 'Iphon',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'The iPhone X display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).',
      isFeatured: true,
      banner: '/images/iphonxbanner.jpg',
    },
    {
      name: 'Macbook Pro',
      slug: 'macbook-pro',
      category: 'Laptops',
      image: '/images/pro.jpg',
      price: 95,
      brand: 'Apple',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'MacBook Pro blasts forward with the M3, M3 Pro and M3 Max chips. Built on 3‑nanometre technology and featuring an all-new GPU architecture, they’re the most advanced chips ever built for a personal computer. And each one brings more pro performance and capability.',
      isFeatured: true,
      banner: '/images/probanner.jpg'
    },
    {
      name: 'MacBook Pro 16',
      slug: 'macbook-pro-16',
      category: 'Laptops',
      image: '/images/pro16.jpg',
      price: 75,
      brand: 'Apple',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'MacBook Pro 16 blasts forward with the M3, M3 Pro and M3 Max chips. Built on 3‑nanometre technology and featuring an all-new GPU architecture, they’re the most advanced chips ever built for a personal computer. And each one brings more pro performance and capability.',
      isFeatured: true,
      banner: '/images/pro16banner.jpg'
    },
    {
      name: 'MacBook Pro with M1 Cheap',
      slug: 'macbook-pro-m1',
      category: 'Laptops',
      image: '/images/m1cheap.jpg',
      price: 75,
      brand: 'Apple',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'MacBook Pro with m1 cheap blasts forward with the M3, M3 Pro and M3 Max chips. Built on 3‑nanometre technology and featuring an all-new GPU architecture, they’re the most advanced chips ever built for a personal computer. And each one brings more pro performance and capability.',
      isFeatured: true,
      banner: '/images/m1cheapbanner.jpg'
    },
  ],
}

export default data
